name: CI

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install pre-commit pytest
      - name: Run pre-commit
        run: pre-commit run --files $(git ls-files '*.py')
      - name: Run tests
        run: pytest -q
