name: ci
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Пиндуем версию Python – гарантируем репродукцию
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - run: python -m pip install --upgrade pip
    - run: pip install -r requirements.txt
    - run: pip install -r requirements-dev.txt  # ruff, mypy, pytest, coverage

    # Прогоняем pre-commit в CI, чтобы локальный и CI набор правил совпадали
    - name: pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files --show-diff-on-failure

    - name: tests
      run: pytest -q --cov=./ --cov-report=xml

    # Публикуем coverage badge (опционально, но красиво)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        flags: cs-lite
        token: ${{ secrets.CODECOV_TOKEN }}
